### PR TITLE
refactor: new ui

### PR DESCRIPTION
**Pull request by TinsFox**
image

### CODE REVIEW

**Comment by TinsFox** [comment]
> this is awesome. can I deploy this?

Of course, but there are still some features that are not completed

**Comment by TinsFox** [comment]
@firefoxOnFire hey, I expect to finish all the development, including the documentation, by tomorrow or this week at the latest. This is actually a remix built website, if you are interested, you can see the PR source code in [TinsFox/smail](https://github.com/TinsFox/smail/tree/main), and then according to apps/remix under the.env.example configuration

**Comment by TinsFox** [comment]
1. New UI, preview here: https://smail-remix.vercel.app/
2. New Doc, preview here: https://smail-doc.pages.dev/

**Comment by TinsFox** [comment]
@firefoxOnFire  Hello, I think I'm almost done. Contains complete new pages and documentation.

If you are interested, you can first pull the new code here to try https://github.com/TinsFox/smail

**Comment by TinsFox** [comment]
@firefoxOnFire Have you filled in all the environment variables? It looks like the DOMAIN variable is missing

**Comment by akazwz** [comment]
@firefoxOnFire Hello, the issue seems to be that one of the environment variables, DOMAINS, is missing. After adding it, the project should be able to start. This pull request has been merged into the next branch, but still requires some modifications.

**Comment by TinsFox** [comment]
Sorry, the variable name should be DOMAINS instead of DOMAIN

**Comment by TinsFox** [comment]
> > Sorry, the variable name should be DOMAINS instead of DOMAIN
> 
> yes, I did this locally and it worked but in vercel even after changing the variable, I am getting the same error.
> New error i got locally is `405 Method Not Allowed`, the same error i got on your demo site.
> Thanks.

Thank you very much for your feedback, I will fix it tomorrow

**Comment by TinsFox** [comment]
> sorry, .env is not being read by the vercel but adding environment variables worked. But I am still getting `405 Method Not Allowed` whenever i click on `create an email account` button. Thanks.

fix it by https://github.com/TinsFox/smail/commit/c5ff7ea5917138ffa0e9c55c14422edc593d471c

**Comment by TinsFox** [comment]
> Sorry, the variable name should be DOMAINS instead of DOMAIN

Documentation has been updated https://github.com/TinsFox/smail/commit/041944bc50d65e6c4a657820d6994ca955bf5f25

**Comment by TinsFox** [comment]
@firefoxOnFire You can open your issue directly at https://github.com/akazwz/smail. It has now been merged into the next branch. However, some minor issues need further modification and have not been merged into the main branch for official release.

**Pull request merged**
